# Generated by Django 2.2.11 on 2020-06-21 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, null=True)),
                ('student_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('student_password', models.CharField(max_length=50, null=True)),
                ('enrollment_no', models.CharField(max_length=10, null=True, unique=True)),
                ('hostel_name', models.CharField(max_length=10, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('roll_no', models.CharField(max_length=20, null=True, unique=True)),
                ('room_no', models.CharField(max_length=5, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=3000, null=True)),
                ('contact', models.CharField(max_length=9999999999, null=True)),
                ('p_contact', models.CharField(max_length=9999999999, null=True)),
                ('image', models.ImageField(default='', upload_to='student/images')),
                ('student', models.BooleanField(default=False)),
                ('warden', models.BooleanField(default=False)),
                ('guard', models.BooleanField(default=False)),
                ('office', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
