# Generated by Django 2.2.11 on 2020-06-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_auto_20200621_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='room_no',
        ),
    ]
