# Generated by Django 2.2.11 on 2020-06-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_remove_userprofile_room_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student_password',
        ),
    ]
