# Generated by Django 2.2.11 on 2020-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_auto_20200621_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='applied_for_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
