# Generated by Django 2.2.11 on 2020-07-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_auto_20200621_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='office',
            new_name='control_room',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_gate',
            field=models.BooleanField(default=False),
        ),
    ]
