# Generated by Django 2.2.11 on 2020-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gatepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=254)),
                ('hostel', models.CharField(max_length=3)),
                ('date_out', models.DateField()),
                ('date_in', models.DateField()),
                ('reason', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=3000)),
                ('s_contact', models.CharField(max_length=9999999999)),
                ('p_contact', models.CharField(max_length=9999999999)),
                ('items', models.CharField(max_length=400)),
            ],
        ),
    ]
