# Generated by Django 2.2.11 on 2020-06-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='p_contact',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='s_contact',
            field=models.CharField(max_length=99),
        ),
    ]
