# Generated by Django 2.2.11 on 2020-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200616_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='p_contact',
            field=models.CharField(max_length=9999999999),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='s_contact',
            field=models.CharField(max_length=9999999999),
        ),
    ]
