# Generated by Django 2.2.11 on 2020-06-19 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200616_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
