# Generated by Django 2.2.11 on 2020-06-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_gatepass_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='hostel',
            field=models.CharField(default='H', max_length=3),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='student_email',
            field=models.EmailField(default='pk@pk.com', max_length=254),
        ),
    ]
