# Generated by Django 2.2.11 on 2020-06-19 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20200619_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
