# Generated by Django 2.2.11 on 2020-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200619_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='id',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='gatepass_id',
            field=models.AutoField(default='0', primary_key=True, serialize=False),
        ),
    ]
