# Generated by Django 2.2.11 on 2020-06-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200620_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='gatepass_id',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
