# Generated by Django 2.2.11 on 2020-06-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200622_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='room_c',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_email',
            field=models.EmailField(default='pk@pk.com', max_length=254),
        ),
    ]
