# Generated by Django 2.2.11 on 2020-06-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200622_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='hostel',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
