# Generated by Django 2.2.11 on 2020-06-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20200622_1801'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='complaints',
        ),
    ]
