# Generated by Django 2.2.13 on 2020-06-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20200623_1722'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table=None,
        ),
    ]
