# Generated by Django 2.2.13 on 2020-06-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20200625_1515'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='complaints',
        ),
    ]
