# Generated by Django 2.2.13 on 2020-06-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20200629_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Disable', 'disable'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Disable', 'disable'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Disable', 'disable'), ('Accepted', 'accepted'), ('Rejected', 'rejected')], default='Active', max_length=10),
        ),
    ]
