# Generated by Django 2.2.11 on 2020-07-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20200630_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='roll',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
