# Generated by Django 2.2.11 on 2020-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_gatepass_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='status',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_control_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='complaint',
            table=None,
        ),
    ]
