# Generated by Django 2.2.11 on 2020-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20200709_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
