# Generated by Django 2.2.11 on 2020-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_gatepass_left_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='approved_control_room_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_control_room_email',
            field=models.EmailField(default='cr@pk.com', max_length=254),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_guard_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_guard_email',
            field=models.EmailField(default='guard@pk.com', max_length=254),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_supervisor_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_supervisor_email',
            field=models.EmailField(default='supervisor@pk.com', max_length=254),
        ),
    ]
