# Generated by Django 2.2.11 on 2020-07-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_auto_20200709_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='active_complaint',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='work_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='work_student',
            field=models.BooleanField(default=False),
        ),
    ]
